"""Serializable model representing a single rule engine finding."""

import uuid
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True, slots=True)
class RuleFinding:
    """A single finding generated by evaluating a rule against a profile.

    Attributes:
        rule_id: The stable namespaced identifier of the rule.
        rule_name: Human-readable name of the rule.
        category: The category of the rule ("quality", "statistical", "leakage").
        severity: The severity of the finding ("info", "warning", "critical").
        column_name: Name of the column this finding applies to, or None if dataset-wide.
        title: Short title summarizing the finding.
        description: Detailed explanation of the finding.
        evidence: Dictionary of metrics or values that triggered the finding.
        confidence: Confidence level in the finding (float between 0.0 and 1.0).
        id: Unique identifier for this finding instance, defaults to a random UUID.
        metadata: Optional dictionary of additional metadata.
    """

    rule_id: str
    rule_name: str
    category: str
    severity: str
    column_name: str | None
    title: str
    description: str
    evidence: Mapping[str, Any]
    confidence: float = 1.0
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Freeze mutable fields to improve immutability consistency."""
        from types import MappingProxyType

        object.__setattr__(self, "evidence", MappingProxyType(dict(self.evidence)))
        object.__setattr__(self, "metadata", MappingProxyType(dict(self.metadata)))
